fail_fast: false
repos:
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.30.0
    hooks:
    - id: check-github-actions
    - id: check-github-workflows
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
    - id: cmake-lint
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
    - id: clang-format
      types_or: [c++]
  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: v1.3.5
  #   hooks:
  #   - id: clang-tidy
  #     args: [-p=build]
  #     files: \.(h|cpp)$
#    - id: oclint
#    - id: cppcheck
#    - id: cpplint
#    - id: include-what-you-use
  - repo: local
    hooks:
    - id: cppcheck
      name: cppcheck
      entry: cppcheck
      language: system
      args:
        [
          --clang=clang,
          --language=c++,
          --std=c++20,
          --enable=all,
          --suppress=unusedFunction,
          --suppress=unmatchedSuppression,
          --suppress=missingIncludeSystem,
          --suppress=toomanyconfigs,
          --error-exitcode=1,
        ]
      files: \.(h|cpp)$
    - id: clang-tidy
      name: clang-tidy
      entry: clang-tidy
      language: system
      args:
        [
          -p=build
        ]
      files: \.(h|cpp)$
