name: coverage

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    uses: ./.github/workflows/devcontainer-command.yml
    with:
      run_cmd: |
        cmake -E make_directory build
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DTRAITS_TEST_COVERAGE=On -S .
        cmake --build build --config Debug --target all
        cmake --build build --config Debug --target test
        cmake --build build --config Debug --target coverage

