name: coverage

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: 'ubuntu-24.04'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check test coverage
      uses: ./.github/actions/devcontainer
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        command: |
          cmake -E make_directory build
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DTRAITS_TEST_COVERAGE=On -S .
          cmake --build build --config Debug --target all
          cmake --build build --config Debug --target test
          cmake --build build --config Debug --target coverage

    - name: Upload test coverage report to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true # optional (default = false)
        disable_search: true # optional (default = false)
        files: ./build/coverage.cobertura.xml # optional
        flags: unittests # optional
        # name: codecov-umbrella # optional
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true # optional (default = false)

    - name: Create test coverage summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: build/**/coverage.cobertura.xml
        badge: true
        format: markdown
        output: both

