name: create package
permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create build environment
        run: cmake -E make_directory build

      - name: Configure CMake
        run: cmake -B ./build

      - name: Create package
        run: cmake --build ./build --target package

      - name: Get package name
        id: package_name
        run: cat ./build/package_name >> "$GITHUB_OUTPUT"

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ steps.package_name.outputs.name }}
          tag: ${{ github.ref }}
