name: deploy package
permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  deploy-package:
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create package
        uses: ./.github/actions/devcontainer
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: |
            cmake -E make_directory build
            cmake -B ./build -S .
            cmake --build ./build --target package

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/${{ github.event.repository.name }}*.zip
          file_glob: true
          tag: ${{ github.ref }}
