name: lint

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: 'ubuntu-24.04'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check pre-commit hooks
      uses: ./.github/actions/devcontainer
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        command: >
          pre-commit run --all-files --show-diff-on-failure
