name: lint

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/devcontainer-command.yml
    with:
      run_cmd: pre-commit run --all-files --show-diff-on-failure
