name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check formatting
      run: |
        find examples include tests -name '*.cpp' -o -name '*.h' |
        xargs clang-format -style=file -i # --dry-run --Werror
