name: create release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    if: github.ref_name == 'main'
    runs-on: 'ubuntu-24.04'

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for tags

      - name: Build package
        uses: ./.github/actions/devcontainer
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: |
            cmake -E make_directory build
            cmake -B ./build -S .
            cmake --build ./build --target package
  
      - name: Set release version
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./build/${{ github.event.repository.name }}*.zip
