name: tests

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run the job on (ubuntu-latest, windows-latest, macos-latest)'
        required: true
        type: string
      cxx_compilers:
        description: 'List of compilers to use'
        required: true
        type: string

jobs:
  tests:
    runs-on: ${{ inputs.os }}
    
    strategy:
      fail-fast: true

      matrix:
        cxx_compiler: ${{ fromJSON(inputs.cxx_compilers) }}
        build_type: [Debug, Release]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup build directory
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake
        -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build tests
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Run tests
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --target test

    - name: Run deployment test
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --target test.deploy

    - name: Run fetch test
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --target test.fetch
